# Generated by Django 5.2.6 on 2025-09-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueimage'),
    ]

    operations = [
    ]
