# Generated by Django 5.2.6 on 2025-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venuebooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
