# Generated by Django 5.2.6 on 2025-09-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_alter_venuebooking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('general', 'General Admission'), ('vip', 'VIP'), ('premium', 'Premium'), ('student', 'Student'), ('early_bird', 'Early Bird'), ('group', 'Group'), ('senior', 'Senior'), ('child', 'Child')], default='general', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Description of what this ticket includes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='venues.venue')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VenueBookingTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='venues.venuebooking')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venueticketcategory')),
            ],
            options={
                'unique_together': {('booking', 'ticket_category')},
            },
        ),
    ]
