# Generated by Django 5.2.6 on 2025-09-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venueticketcategory_venuebookingticketitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueticketcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='venueticketcategory',
            name='venue',
        ),
        migrations.DeleteModel(
            name='VenueBookingTicketItem',
        ),
        migrations.DeleteModel(
            name='VenueTicketCategory',
        ),
    ]
