# Generated by Django 5.2.6 on 2025-09-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venuecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_comments/'),
        ),
    ]
