# Generated by Django 5.2.6 on 2025-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleupgraderequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleupgraderequest',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company/Organization name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roleupgraderequest',
            name='experience',
            field=models.TextField(blank=True, help_text='Relevant experience', null=True),
        ),
        migrations.AddField(
            model_name='roleupgraderequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roleupgraderequest',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Portfolio or website URL', null=True),
        ),
        migrations.AlterField(
            model_name='roleupgraderequest',
            name='reason',
            field=models.TextField(help_text='Why do you want this role?'),
        ),
    ]
