# Generated by Django 5.2.6 on 2025-10-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_message_content_messagefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefile',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
