# Generated by Django 5.2.6 on 2025-09-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticketcategory_eventbooking_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='attendee_email',
            field=models.EmailField(blank=True, help_text='Email address of the ticket holder', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='attendee_name',
            field=models.CharField(blank=True, help_text='Full name of the ticket holder', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='attendee_phone',
            field=models.CharField(blank=True, help_text='Phone number of the ticket holder', max_length=15, null=True),
        ),
    ]
