# Generated by Django 5.2.6 on 2025-09-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventbooking_amount_eventbooking_attendee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='ticket_category',
        ),
        migrations.CreateModel(
            name='BookingTicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, help_text='Price at time of booking', max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='events.eventbooking')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='events.ticketcategory')),
            ],
            options={
                'unique_together': {('booking', 'ticket_category')},
            },
        ),
    ]
