# Generated by Django 5.2.6 on 2025-10-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcomment_eventcommentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcommentlike',
            options={},
        ),
    ]
