# Generated by Django 5.2.6 on 2025-09-28 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('event_booking', 'Event Booking'), ('venue_booking', 'Venue Booking'), ('booking_confirmation', 'Booking Confirmation'), ('event_reminder', 'Event Reminder'), ('payment_success', 'Payment Success'), ('venue_booking_request', 'Venue Booking Request'), ('event_registration', 'Event Registration'), ('system', 'System Notification')], default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
    ]
