# Generated by Django 5.2.6 on 2025-10-02 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_eventreview_venuereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreview',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='eventreview',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='eventreview',
            name='comment',
            field=models.TextField(blank=True, help_text='Your detailed review about the event', null=True),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='title',
            field=models.CharField(default='Review', help_text='Brief title for your review', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='organization_rating',
            field=models.IntegerField(help_text='Rating for event organization (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.IntegerField(help_text='Overall rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='value_rating',
            field=models.IntegerField(help_text='Rating for value for money (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='venue_rating',
            field=models.IntegerField(help_text='Rating for venue quality (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='VenueReview',
        ),
    ]
