# Generated by Django 5.2.6 on 2025-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_eventreview_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreview',
            name='title',
            field=models.CharField(help_text='Brief title for your review', max_length=200),
        ),
    ]
