# Generated by Django 5.2.6 on 2025-09-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('event_booking_confirm', 'Event Booking Confirmation'), ('venue_booking_status', 'Venue Booking Status'), ('upcoming_event', 'Upcoming Event'), ('venue_booking_request', 'Venue Booking Request'), ('event_registration', 'Event Registration'), ('system', 'System Notification')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('venue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
